### ISSUE TITLE
Question about CommandHandler class

### ISSUE THREAD

**Issue by prolic** [prooph/annotations#3]
see: https://github.com/mrook/annotations/blob/master/src/CommandHandler.php#L18

what is this class for? it does nothing?!

**Comment by prolic** [comment]
same here: https://github.com/mrook/annotations/blob/master/src/EventHandler.php

**Comment by prolic** [comment]
same here: https://github.com/mrook/annotations/blob/master/src/TargetAggregateIdentifier.php#L18

**Comment by mrook** [comment]
These are annotation classes.

**Comment by prolic** [comment]
Maybe put them in another namespace?

Am 20.02.2017 16:20 schrieb "Michiel Rook" <notifications@github.com>:

**Comment by mrook** [comment]
Why?

**Comment by prolic** [comment]
There is no technical reason of course. I look into a directory and see
what I can use. If there is something only needed for internal stuff, not
useful to the outside world, I tend to move it away there.

Am 20.02.2017 16:38 schrieb "Michiel Rook" <notifications@github.com>:

**Comment by mrook** [comment]
These classes are explicitly intended for use by the outside world, i.e.:

```
use Prooph\Annotation\EventHandler;

/**
 * @EventHandler
 */
public function onSomething()
{
}
```

**Comment by prolic** [comment]
ok
