### ISSUE TITLE
Comment about EventHandlerInvoker

### ISSUE THREAD

**Issue by prolic** [prooph/annotations#5]
Why is reflection used here at all? The handler method should be a public method, so it can get called directly without the use of reflection.

**Comment by mrook** [comment]
I'm not entirely convinced handlers should always be public - at least not for event handlers, possibly for command handlers.

**Comment by prolic** [comment]
Ok agree

Am 20.02.2017 16:21 schrieb "Michiel Rook" <notifications@github.com>:
